"""
Phase 1.3 — Seed Question Bank Generator.

Pipeline:
processed seed JSON
    -> structured semantic chunks
    -> Groq MCQ generation
    -> validation
    -> quality scoring
    -> option shuffling
    -> deduplication
    -> question_bank.json

All generated questions are marked as SANDBOX DATA.

The generator is checkpointed after every chunk so an interrupted
API run can resume without throwing away previously accepted questions.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Any

from ml_pipeline.chunker import chunk_structured_document
from ml_pipeline.mcq_generator import generate_mcqs
from ml_pipeline.mcq_scorer import score_mcq_quality, shuffle_mcq_options
from ml_pipeline.mcq_validator import validate_mcqs


BASE_DIR = Path(__file__).resolve().parent
SEED_DIR = BASE_DIR / "seed_content"
PROCESSED_DIR = SEED_DIR / "processed"

MANIFEST_PATH = SEED_DIR / "manifest.json"
CHECKPOINT_PATH = SEED_DIR / "question_bank_checkpoint.json"
FINAL_PATH = SEED_DIR / "question_bank.json"


# ---------------------------------------------------------------------------
# Generation configuration
# ---------------------------------------------------------------------------

TARGET_QUESTIONS = 200

# Small API batches protect against Groq token-per-minute limits.
QUESTIONS_PER_CALL = 3

# Only questions above this score enter the final bank.
QUALITY_THRESHOLD = 0.55

# Chunker target specifically designed for MCQ generation.
CHUNK_TARGET = "mcq"

# Difficulty distribution.
DIFFICULTY_PLAN = {
    "easy": 70,
    "medium": 80,
    "hard": 50,
}

# Optional safety limit during development.
# None means process all available chunks.
MAX_CHUNKS_PER_DOCUMENT = None

# Delay between API calls.
API_DELAY_SECONDS = 0.5


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> dict[str, Any]:
    """Load a JSON object from disk."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: Path, data: dict[str, Any]) -> None:
    """Write JSON with UTF-8 encoding."""
    temporary_path = path.with_suffix(".tmp")

    with open(temporary_path, "w", encoding="utf-8") as f:
        json.dump(
            data,
            f,
            indent=2,
            ensure_ascii=False,
        )

    os.replace(temporary_path, path)


def load_manifest() -> dict[str, Any]:
    """Load seed-content manifest."""
    if not MANIFEST_PATH.exists():
        raise FileNotFoundError(
            f"Manifest not found: {MANIFEST_PATH}"
        )

    return load_json(MANIFEST_PATH)


def load_checkpoint() -> dict[str, Any]:
    """
    Load the generation checkpoint.

    The checkpoint stores accepted questions and processed chunk IDs.
    """
    if not CHECKPOINT_PATH.exists():
        return {
            "questions": [],
            "processed_chunks": [],
            "failed_chunks": [],
        }

    try:
        data = load_json(CHECKPOINT_PATH)

        if not isinstance(data, dict):
            raise ValueError("Checkpoint must contain a JSON object.")

        data.setdefault("questions", [])
        data.setdefault("processed_chunks", [])
        data.setdefault("failed_chunks", [])

        return data

    except Exception as exc:
        print(f"WARNING: Could not load checkpoint: {exc}")
        print("Starting a new checkpoint.")

        return {
            "questions": [],
            "processed_chunks": [],
            "failed_chunks": [],
        }


def save_checkpoint(state: dict[str, Any]) -> None:
    """Save checkpoint after each processed chunk."""
    save_json(CHECKPOINT_PATH, state)


# ---------------------------------------------------------------------------
# Document helpers
# ---------------------------------------------------------------------------

def load_processed_pages(document_meta: dict[str, Any]) -> list[dict[str, Any]]:
    """
    Load the page-level structured output generated by document_processor.
    """
    relative_path = document_meta.get("processed_file")

    if not relative_path:
        raise ValueError(
            f"No processed_file specified for "
            f"{document_meta.get('document_id')}"
        )

    path = BASE_DIR.parent / relative_path

    if not path.exists():
        raise FileNotFoundError(
            f"Processed file not found: {path}"
        )

    document = load_json(path)

    pages = document.get("pages")

    if not isinstance(pages, list):
        raise ValueError(
            f"Processed file does not contain a 'pages' list: {path}"
        )

    return pages


def build_chunks(
    pages: list[dict[str, Any]],
    document_id: str,
) -> list[dict[str, Any]]:
    """
    Use the existing structured semantic chunker with the MCQ target.
    """
    chunks = chunk_structured_document(
        pages,
        target=CHUNK_TARGET,
        source_id=document_id,
    )

    if not isinstance(chunks, list):
        raise TypeError(
            "chunk_structured_document() must return a list."
        )

    return chunks


# ---------------------------------------------------------------------------
# Question helpers
# ---------------------------------------------------------------------------

def normalize_question(question: str) -> str:
    """Normalize question text for exact duplicate detection."""
    return " ".join(
        str(question).lower().strip().split()
    )


def existing_question_keys(
    questions: list[dict[str, Any]],
) -> set[str]:
    """Build normalized question lookup set."""
    return {
        normalize_question(item.get("question", ""))
        for item in questions
        if item.get("question")
    }


def difficulty_counts(
    questions: list[dict[str, Any]],
) -> dict[str, int]:
    """Count accepted questions by difficulty."""
    counts = {
        difficulty: 0
        for difficulty in DIFFICULTY_PLAN
    }

    for question in questions:
        difficulty = question.get("difficulty")

        if difficulty in counts:
            counts[difficulty] += 1

    return counts


def choose_difficulty(
    questions: list[dict[str, Any]],
) -> str:
    """
    Select the difficulty with the largest remaining quota.
    """
    counts = difficulty_counts(questions)

    remaining = {
        difficulty:
            DIFFICULTY_PLAN[difficulty] - counts[difficulty]
        for difficulty in DIFFICULTY_PLAN
    }

    available = {
        difficulty: remaining_count
        for difficulty, remaining_count in remaining.items()
        if remaining_count > 0
    }

    if not available:
        return "medium"

    return max(
        available,
        key=available.get,
    )


def attach_provenance(
    mcq: dict[str, Any],
    document_meta: dict[str, Any],
    chunk: dict[str, Any],
) -> dict[str, Any]:
    """
    Attach source traceability to every accepted question.
    """
    result = dict(mcq)

    result["sandbox_data"] = True

    result["source"] = {
        "document_id": document_meta.get("document_id"),
        "filename": document_meta.get("filename"),
        "title": document_meta.get("title"),
        "source": document_meta.get("source"),
        "source_url": document_meta.get("source_url"),
        "topic": document_meta.get("topic"),
        "chunk_id": chunk.get("chunk_id"),
        "page_number": chunk.get("page_number"),
        "page_numbers": chunk.get("page_numbers", []),
    }

    # Internal field used only for debugging/checkpoint validation.
    result["_source_chunk"] = chunk.get("text", "")

    return result


def remove_internal_fields(
    questions: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Remove internal generation-only fields."""
    cleaned = []

    for question in questions:
        item = dict(question)
        item.pop("_source_chunk", None)
        cleaned.append(item)

    return cleaned


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_batch(
    chunk: dict[str, Any],
    document_meta: dict[str, Any],
    difficulty: str,
    state: dict[str, Any],
) -> int:
    """
    Generate one small batch and return accepted-question count.
    """
    source_text = str(chunk.get("text", "")).strip()

    if not source_text:
        print("  Empty chunk — skipped.")
        return 0

    competency = (
        document_meta.get("topic")
        or "Official Statistics"
    )

    print(
        f"  API request: {QUESTIONS_PER_CALL} "
        f"{difficulty} MCQs"
    )
    print(
        f"  Competency: {competency}"
    )
    print(
        f"  Source size: {len(source_text):,} characters"
    )

    try:
        generated = generate_mcqs(
            source_text,
            competency,
            QUESTIONS_PER_CALL,
            difficulty,
        )

    except Exception as exc:
        print(
            f"  GENERATION FAILED: "
            f"{type(exc).__name__}: {exc}"
        )
        return 0

    print(
        f"  Generated {len(generated)} candidate questions."
    )

    # ---------------------------------------------------------------
    # Validation
    # ---------------------------------------------------------------

    validation_results = validate_mcqs(
        generated,
        source_text,
    )

    # ---------------------------------------------------------------
    # Existing duplicate lookup
    # ---------------------------------------------------------------

    existing_keys = existing_question_keys(
        state["questions"]
    )

    accepted = 0

    for index, (mcq, validation) in enumerate(
        zip(generated, validation_results)
    ):
        if not validation["valid"]:
            print(
                f"    [{index}] REJECT — validation"
            )

            for issue in validation["issues"]:
                print(f"        - {issue}")

            continue

        # -----------------------------------------------------------
        # Quality scoring
        # -----------------------------------------------------------

        scored = score_mcq_quality(
            mcq,
            source_text,
        )

        quality_score = scored.get(
            "quality_score",
            0.0,
        )

        print(
            f"    [{index}] quality={quality_score:.3f}"
        )

        if quality_score < QUALITY_THRESHOLD:
            print(
                f"        REJECT — below "
                f"{QUALITY_THRESHOLD:.2f} threshold"
            )
            continue

        # -----------------------------------------------------------
        # Exact duplicate detection
        # -----------------------------------------------------------

        normalized = normalize_question(
            scored.get("question", "")
        )

        if not normalized:
            print("        REJECT — empty question")
            continue

        if normalized in existing_keys:
            print("        REJECT — duplicate question")
            continue

        # -----------------------------------------------------------
        # Option position randomization
        # -----------------------------------------------------------

        shuffled = shuffle_mcq_options(
            scored
        )

        # -----------------------------------------------------------
        # Provenance
        # -----------------------------------------------------------

        final_item = attach_provenance(
            shuffled,
            document_meta,
            chunk,
        )

        state["questions"].append(final_item)
        existing_keys.add(normalized)

        accepted += 1

        print("        ACCEPT")

    return accepted


# ---------------------------------------------------------------------------
# Final output
# ---------------------------------------------------------------------------

def write_final_bank(
    questions: list[dict[str, Any]],
) -> None:
    """Write the final learner-facing question bank."""
    questions = questions[:TARGET_QUESTIONS]

    cleaned = remove_internal_fields(
        questions
    )

    payload = {
        "metadata": {
            "dataset_name": "GyanSetu Seed Question Bank",
            "sandbox_data": True,
            "status": "SANDBOX DATA",
            "target_questions": TARGET_QUESTIONS,
            "generated_questions": len(cleaned),
            "difficulty_distribution": difficulty_counts(
                cleaned
            ),
            "quality_threshold": QUALITY_THRESHOLD,
        },
        "questions": cleaned,
    }

    save_json(
        FINAL_PATH,
        payload,
    )


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 70)
    print("GYANSETU — PHASE 1.3 QUESTION BANK GENERATOR")
    print("=" * 70)
    print()
    print(f"Target: {TARGET_QUESTIONS}")
    print(f"Questions/API call: {QUESTIONS_PER_CALL}")
    print(f"Quality threshold: {QUALITY_THRESHOLD}")
    print(f"Chunk target: {CHUNK_TARGET}")
    print()

    manifest = load_manifest()
    state = load_checkpoint()

    questions = state["questions"]

    print(
        f"Checkpoint contains "
        f"{len(questions)} accepted questions."
    )

    # If target already reached, only regenerate final output.
    if len(questions) >= TARGET_QUESTIONS:
        write_final_bank(
            questions
        )

        print(
            f"Target already reached. "
            f"Final bank: {FINAL_PATH}"
        )
        return

    documents = manifest.get(
        "documents",
        [],
    )

    if not documents:
        raise RuntimeError(
            "No documents found in manifest."
        )

    # ---------------------------------------------------------------
    # Process every seed document
    # ---------------------------------------------------------------

    for document_meta in documents:

        if len(state["questions"]) >= TARGET_QUESTIONS:
            break

        document_id = document_meta.get(
            "document_id",
            "unknown",
        )

        title = document_meta.get(
            "title",
            document_id,
        )

        print()
        print("=" * 70)
        print(f"DOCUMENT: {title}")
        print(f"ID: {document_id}")
        print("=" * 70)

        try:
            pages = load_processed_pages(
                document_meta
            )

            print(
                f"Pages loaded: {len(pages)}"
            )

            chunks = build_chunks(
                pages,
                document_id,
            )

            print(
                f"MCQ chunks: {len(chunks)}"
            )

        except Exception as exc:
            print(
                f"DOCUMENT FAILED: "
                f"{type(exc).__name__}: {exc}"
            )
            continue

        if MAX_CHUNKS_PER_DOCUMENT is not None:
            chunks = chunks[
                :MAX_CHUNKS_PER_DOCUMENT
            ]

        # -----------------------------------------------------------
        # Process chunks
        # -----------------------------------------------------------

        for chunk_index, chunk in enumerate(
            chunks
        ):

            if len(state["questions"]) >= TARGET_QUESTIONS:
                break

            chunk_id = chunk.get(
                "chunk_id",
                f"{document_id}_{chunk_index}",
            )

            # Resume support.
            if chunk_id in state[
                "processed_chunks"
            ]:
                continue

            print()
            print(
                f"Chunk "
                f"{chunk_index + 1}/{len(chunks)}"
            )
            print(
                f"Chunk ID: {chunk_id}"
            )
            print(
                f"Pages: "
                f"{chunk.get('page_numbers', [])}"
            )

            difficulty = choose_difficulty(
                state["questions"]
            )

            accepted = generate_batch(
                chunk,
                document_meta,
                difficulty,
                state,
            )

            # Mark chunk complete regardless of whether the API
            # returned usable questions. This prevents infinite
            # regeneration loops during a resume.
            state[
                "processed_chunks"
            ].append(chunk_id)

            if accepted == 0:
                state[
                    "failed_chunks"
                ].append({
                    "chunk_id": chunk_id,
                    "document_id": document_id,
                })

            save_checkpoint(
                state
            )

            print(
                f"Accepted this chunk: {accepted}"
            )
            print(
                f"TOTAL: "
                f"{len(state['questions'])}/"
                f"{TARGET_QUESTIONS}"
            )

            time.sleep(
                API_DELAY_SECONDS
            )

    # ---------------------------------------------------------------
    # Finalize
    # ---------------------------------------------------------------

    write_final_bank(
        state["questions"]
    )

    print()
    print("=" * 70)
    print("QUESTION BANK GENERATION FINISHED")
    print("=" * 70)
    print(
        f"Accepted: "
        f"{min(len(state['questions']), TARGET_QUESTIONS)}"
    )
    print(
        f"Difficulty: "
        f"{difficulty_counts(state['questions'])}"
    )
    print(
        f"Checkpoint: {CHECKPOINT_PATH}"
    )
    print(
        f"Final bank: {FINAL_PATH}"
    )
    print("=" * 70)


if __name__ == "__main__":
    main()