"""create phase 1 schema

Revision ID: f79ac6f66ac6
Revises: 
Create Date: 2026-09-05 17:01:42.495044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f79ac6f66ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_name'), 'competencies', ['name'], unique=False)
    op.create_index(op.f('ix_competencies_role_id'), 'competencies', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('competency_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_diversity', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_states_competency_id'), 'competency_states', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_states_user_id'), 'competency_states', ['user_id'], unique=False)
    op.create_table('subskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subskills_competency_id'), 'subskills', ['competency_id'], unique=False)
    op.create_index(op.f('ix_subskills_name'), 'subskills', ['name'], unique=False)
    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('subskill_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('options_json', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('correct_option', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['subskill_id'], ['subskills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_items_competency_id'), 'assessment_items', ['competency_id'], unique=False)
    op.create_index(op.f('ix_assessment_items_subskill_id'), 'assessment_items', ['subskill_id'], unique=False)
    op.create_index(op.f('ix_assessment_items_user_id'), 'assessment_items', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('subskill_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('evidence_metadata', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['subskill_id'], ['subskills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_competency_id'), 'evidence', ['competency_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_subskill_id'), 'evidence', ['subskill_id'], unique=False)
    op.create_index(op.f('ix_evidence_user_id'), 'evidence', ['user_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('subskill_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intervention_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['subskill_id'], ['subskills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_competency_id'), 'interventions', ['competency_id'], unique=False)
    op.create_index(op.f('ix_interventions_intervention_type'), 'interventions', ['intervention_type'], unique=False)
    op.create_index(op.f('ix_interventions_subskill_id'), 'interventions', ['subskill_id'], unique=False)
    op.create_index(op.f('ix_interventions_user_id'), 'interventions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_user_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_subskill_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_intervention_type'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_competency_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_evidence_user_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_subskill_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_competency_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_assessment_items_user_id'), table_name='assessment_items')
    op.drop_index(op.f('ix_assessment_items_subskill_id'), table_name='assessment_items')
    op.drop_index(op.f('ix_assessment_items_competency_id'), table_name='assessment_items')
    op.drop_table('assessment_items')
    op.drop_index(op.f('ix_subskills_name'), table_name='subskills')
    op.drop_index(op.f('ix_subskills_competency_id'), table_name='subskills')
    op.drop_table('subskills')
    op.drop_index(op.f('ix_competency_states_user_id'), table_name='competency_states')
    op.drop_index(op.f('ix_competency_states_competency_id'), table_name='competency_states')
    op.drop_table('competency_states')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_competencies_role_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_name'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
